config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root :to => "places#top"
  resources :places

  get '/about' => 'places#about'
  get '/map' => 'places#map', as: :map

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  #Mounts paperclip image
  belongs_to :place
  has_attached_file :image
  #This validates the type of file uploaded. According to this, only images are allowed.
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #Index action, photos gets listed in the order at which they were created
  def index
    @photos = Photo.order('created_at')
  end

  #New action for creating a new photo
  def new
    @photo = Photo.new
  end

  #Create action ensures that submitted photo gets created if it meets the requirements
  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:notice] = "Successfully added new photo!"
      redirect_to root_path
    else
      flash[:alert] = "Error adding new photo!"
      render :new
    end
  end

  private

  #Permitted parameters when creating a photo. This is used for security reasons.
  def photo_params
    params.require(:photo).permit(:title, :image)
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :photos
  serialize :hours
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  #Index action, photos gets listed in the order at which they were created
  def index
    @photos = Photo.order('created_at')
  end

  #New action for creating a new photo
  def new
    @photo = Photo.new
  end

  #Create action ensures that submitted photo gets created if it meets the requirements
  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:notice] = "Successfully added new photo!"
      redirect_to root_path
    else
      flash[:alert] = "Error adding new photo!"
      render :new
    end
  end

  private

  #Permitted parameters when creating a photo. This is used for security reasons.
  def photo_params
    params.require(:photo).permit(:title, :image)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  if Rails.env == 'production'
    before_action :authenticate_user!, only: [:edit, :update, :destroy]
  end

  def top
    @places_num = Place.all.size
  end

  def index
    @q = Place.ransack(params[:q])
    if params[:prefecture].present?
      @prefecture = params[:prefecture]
      @places = Place.where(prefecture: params[:prefecture]).page(params[:page])
    elsif params[:q].present?
      @places = @q.result(distinct: true).page(params[:page])
    else
      @places = Place.all.page(params[:page])
    end
  end

  def map
    @places = Place.all
    @get_current = 'true' if params[:current].present?
    @search_latlng = Geocoder.search(params[:search], params: {language: :ja}).first.geometry["location"] if params[:search].present?
  end

  def about
  end

  def show
  end

  def new
    @place = Place.new
  end

  def edit
    gon.hours = @place.hours
  end

  def create
    @place = Place.new(place_params)
    @place.hours = JSON.parse(params[:place][:hours]) if params[:place][:hours].present?
    if @place.save && params[:photo].present?
      # params[:photo] will be an array.
      # you can check total number of photos selected using params[:photo].count
      @place.photos.create(title: params[:photo].original_filename, image: params[:photo], source: params[:source] )
    end
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: '新規卓球場の登録ありがとうございます。' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @place.save && params[:photo].present?
      @place.photos.create(title: params[:photo].original_filename, image: params[:photo], source: params[:source] )
    end
    respond_to do |format|
      if @place.update(place_params)
        if params[:place][:hours].present?
          @place.hours = JSON.parse(params[:place][:hours]) 
          @place.save
        end
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:title, :url, :latitude, :longitude, :content, :address, :source, :hours)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper

  def num_to_day(array)
    day_array = ['月', '火', '水', '木', '金', '土', '日']
    result = []
    array.each do |num|
      result.push(day_array[num.to_i - 1])
    end
    result.join(', ')
  end

  def sym_to_day(symbol)
    case symbol
    when 'mon' then '月'
    when 'tue' then '火'
    when 'wed' then '水'
    when 'thu' then '木'
    when 'fri' then '金'
    when 'sat' then '土'
    when 'sun' then '日'
    end
  end

  def show_hours(place)

    #全曜日共通の場合
    if place.hours.present? && place.hours['common_flag'] == true

      string = "<p>#{place.hours['hours']['open']} ~ #{place.hours['hours']['close']}</p>"
      if place.hours['closed_days'].present?
        string += "</div><div class='show_other show-part'>
          <strong>休館日</strong>
          <p>#{num_to_day(place.hours['closed_days'])}</p>"
      end
      string

    #曜日毎に異なる場合
    elsif place.hours.present? && place.hours['common_flag'] == false

      string = "<ul>"
      ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'].each do |symbol|
        if place.hours['hours'][symbol].present?
          string += "<li>#{sym_to_day(symbol)}: #{place.hours['hours'][symbol]['open']} ~ #{place.hours['hours'][symbol]['close']}</li>"
        end
      end
      string += "</ul>"
      string

    #hoursが未登録の場合
    else
      "<p>未登録</p>"
    end

  end

  def show_hours_twitter(place)

    #全曜日共通の場合
    if place.hours.present? && place.hours['common_flag'] == true

      string = "#{place.hours['hours']['open']} ~ #{place.hours['hours']['close']}</p>"
      if place.hours['closed_days'].present?
        string += "休館日： #{num_to_day(place.hours['closed_days'])}"
      end
      string

    #曜日毎に異なる場合
    elsif place.hours.present? && place.hours['common_flag'] == false

      string = "<br><ul>"
      ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'].each do |symbol|
        if place.hours['hours'][symbol].present?
          string += "<li>#{sym_to_day(symbol)}: #{place.hours['hours'][symbol]['open']} ~ #{place.hours['hours'][symbol]['close']}</li>"
        end
      end
      string += "</ul>"
      string

    #hoursが未登録の場合
    else
      "未登録"
    end

  end

end

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-99596730-1', 'auto');
  ga('send', 'pageview');
  console.log('google analytics running');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>卓球マップ</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <!-- bootstrap javascripts -->
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  <!-- bootstrap stylesheet -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <!-- google japanese font -->
  <link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" rel="stylesheet" />


  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <!-- jquery timepicker -->
  <%= javascript_include_tag 'jquery_timepicker' %>
  <%= stylesheet_link_tag    'jquery_timepicker', media: 'all' %>

  <!-- Gon : use ruby variables in javascript -->
  <%= Gon::Base.render_data %>

  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>-<%= action_name %>">

  <nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-faded wf-mplus1p navbar-<%= controller_name %>-<%= action_name %>">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand li_head" href="/">卓球マップ</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">トップ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/map">マップ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/places">卓球場一覧</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/places/new">卓球場を登録</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">当サイトについて</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container yield_container">
    <%= yield %>
  </div>

  <footer class="footer"></footer>

  <!-- analytics script -->
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/places/about.html.erb
<div class='about_text container'>
  <div class='row'>
    <div class='col-xs-2'></div>
    <div class='col-xs-8'>
      <h1 class='wf-mplus1p about_title'>卓球マップについて</h1>
      <br>
      <p class='wf-mplus1p'>当サイトは、全国の卓球愛好者のために作られた練習場所検索サービスです。</p>
      <p class='wf-mplus1p'>練習場所が見つからない、練習場所を増やしたいといった課題を克服するために作られたものです。</p>
      <p class='wf-mplus1p'>ご意見、ご要望がある方は下記の連絡先までお問い合わせください。</p>
      <br>
      <p class='wf-mplus1p' style='text-align:center; font-size: 2.5em;'>takkyuumap@gmail.com</p>
      <br>
    </div>
    <div class='col-xs-2'></div>
  </div>
  <div class='row'>
    <div class='col-xs-4'></div>
    <div class='col-xs-4 news'>
      <div class='news-child'>
        <div class='text-center'>~新着情報~</div>
        <ul>
          <li>07/01  営業時間登録機能を追加</li>
          <li>06/01  一覧ページに文字列検索機能追加</li>
          <li>05/26  一覧ページに都道府県絞り込み機能追加</li>
          <li>05/24 「現在地から検索」機能追加</li>
        </ul>
      </div>
    </div>
    <div class='col-xs-4'></div>
  </div>
  <br>
</div>

app/views/places/edit.html.erb
<h1 class='edit-title'>卓球場を編集</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class='wf-mplus1p index_title' style="font-weight: 400;">
  <% if @prefecture.present? %>
    <%= @prefecture %>の<% end %>卓球場一覧
</h1>

<div class="d-flex search-div">
  <div class="row justify-content-around">

    <div class="dropdown search col-xs-4">
      <button class="btn btn-original dropdown-toggle" type="button" data-toggle="dropdown">都道府県絞り込み</button>
      <div class="dropdown-menu">
        <%= link_to '東京都', places_path(prefecture: '東京都'), class: 'dropdown-item' %>
        <%= link_to '神奈川県', places_path(prefecture: '神奈川県'), class: 'dropdown-item' %>
        <%= link_to '千葉県', places_path(prefecture: '千葉県'), class: 'dropdown-item' %>
        <%= link_to '埼玉県', places_path(prefecture: '埼玉県'), class: 'dropdown-item' %>
        <%= link_to '茨城県', places_path(prefecture: '茨城県'), class: 'dropdown-item' %>
        <%= link_to '群馬県', places_path(prefecture: '群馬県'), class: 'dropdown-item' %>
        <%= link_to '栃木県', places_path(prefecture: '栃木県'), class: 'dropdown-item' %>
        <%= link_to '北海道', places_path(prefecture: '北海道'), class: 'dropdown-item' %>
        <%= link_to '青森県', places_path(prefecture: '青森県'), class: 'dropdown-item' %>
        <%= link_to '秋田県', places_path(prefecture: '秋田県'), class: 'dropdown-item' %>
        <%= link_to '岩手県', places_path(prefecture: '岩手県'), class: 'dropdown-item' %>
        <%= link_to '山形県', places_path(prefecture: '山形県'), class: 'dropdown-item' %>
        <%= link_to '宮城県', places_path(prefecture: '宮城県'), class: 'dropdown-item' %>
        <%= link_to '福島県', places_path(prefecture: '福島県'), class: 'dropdown-item' %>
        <%= link_to '新潟県', places_path(prefecture: '新潟県'), class: 'dropdown-item' %>
        <%= link_to '長野県', places_path(prefecture: '長野県'), class: 'dropdown-item' %>
        <%= link_to '富山県', places_path(prefecture: '富山県'), class: 'dropdown-item' %>
        <%= link_to '石川県', places_path(prefecture: '石川県'), class: 'dropdown-item' %>
        <%= link_to '岐阜県', places_path(prefecture: '岐阜県'), class: 'dropdown-item' %>
        <%= link_to '山梨県', places_path(prefecture: '山梨県'), class: 'dropdown-item' %>
        <%= link_to '静岡県', places_path(prefecture: '静岡県'), class: 'dropdown-item' %>
        <%= link_to '愛知県', places_path(prefecture: '愛知県'), class: 'dropdown-item' %>
        <%= link_to '福井県', places_path(prefecture: '福井県'), class: 'dropdown-item' %>
        <%= link_to '滋賀県', places_path(prefecture: '滋賀県'), class: 'dropdown-item' %>
        <%= link_to '三重県', places_path(prefecture: '三重県'), class: 'dropdown-item' %>
        <%= link_to '京都府', places_path(prefecture: '京都府'), class: 'dropdown-item' %>
        <%= link_to '大阪府', places_path(prefecture: '大阪府'), class: 'dropdown-item' %>
        <%= link_to '奈良県', places_path(prefecture: '奈良県'), class: 'dropdown-item' %>
        <%= link_to '和歌山県', places_path(prefecture: '和歌山県'), class: 'dropdown-item' %>
        <%= link_to '兵庫県', places_path(prefecture: '兵庫県'), class: 'dropdown-item' %>
        <%= link_to '鳥取県', places_path(prefecture: '鳥取県'), class: 'dropdown-item' %>
        <%= link_to '岡山県', places_path(prefecture: '岡山県'), class: 'dropdown-item' %>
        <%= link_to '広島県', places_path(prefecture: '広島県'), class: 'dropdown-item' %>
        <%= link_to '島根県', places_path(prefecture: '島根県'), class: 'dropdown-item' %>
        <%= link_to '山口県', places_path(prefecture: '山口県'), class: 'dropdown-item' %>
        <%= link_to '香川県', places_path(prefecture: '香川県'), class: 'dropdown-item' %>
        <%= link_to '徳島県', places_path(prefecture: '徳島県'), class: 'dropdown-item' %>
        <%= link_to '高知県', places_path(prefecture: '高知県'), class: 'dropdown-item' %>
        <%= link_to '愛媛県', places_path(prefecture: '愛媛県'), class: 'dropdown-item' %>
        <%= link_to '福岡県', places_path(prefecture: '福岡県'), class: 'dropdown-item' %>
        <%= link_to '大分県', places_path(prefecture: '大分県'), class: 'dropdown-item' %>
        <%= link_to '熊本県', places_path(prefecture: '熊本県'), class: 'dropdown-item' %>
        <%= link_to '宮崎県', places_path(prefecture: '宮崎県'), class: 'dropdown-item' %>
        <%= link_to '鹿児島県', places_path(prefecture: '鹿児島県'), class: 'dropdown-item' %>
        <%= link_to '佐賀県', places_path(prefecture: '佐賀県'), class: 'dropdown-item' %>
        <%= link_to '長崎県', places_path(prefecture: '長崎県'), class: 'dropdown-item' %>
        <%= link_to '沖縄県', places_path(prefecture: '沖縄県'), class: 'dropdown-item' %>
      </div>
    </div>

    <div class="search col-xs-4">
      <%= search_form_for @q do |f| %>
        <div class="input-group title-search">
          <%= f.search_field :title_cont, class: 'form-control', placeholder:'名前を検索' %>
          <span class="input-group-btn">
            <button class="btn btn-original" type="submit">検索</button>
          </span>
        </div>
      <% end %>
    </div>

    <div class="search col-xs-4">
      <button class="btn btn-original" type="button" href="/places"><span class="mobile_hide">絞り込みを</span>元に戻す</button>
    </div>

  </div>
</div>

<div class="d-flex card-grid">
  <div class="row justify-content-around">
    <% @places.each do |place| %>

      <div class="card wf-mplus1p">
        <% if place.photos.present? %>
          <% place.photos.each do |photo| %>
            <%= image_tag photo.image.url, class: 'card-img-top' %>
          <% end %>
        <% else %>
          <%= image_tag '/assets/images/no_photo_available.jpg', class: 'card-img-top' %>
        <% end %>
        <div class="card-block">
          <h4 class="card-title"><%= place.title %></h4>
          <p class="card-text">
            <% if place.address.size > 0 %>
              <%= place.address %>
            <% else %>
              住所未登録
            <% end %>
          </p>
        </div>
        <div class="card-footer">
          <%= link_to '詳細', place, class:'btn btn-original show_btn' %>
          <% if place.url.present? %>
            <%= link_to 'HP', place.url, class:'btn btn-original show_btn' %>
          <% end %>
        </div>
      </div>

    <% end %>
  </div>
</div>

<div class="d-flex">
  <div class="row justify-content-center">
    <div class="col-xs-12">
      <%= paginate @places, window: 2, theme: 'custom_theme' %>
    </div>
  </div>
</div>
<div class="d-flex">
  <div class="row justify-content-center">
    <div class="col-xs-12 page-numbers">
      <%= page_entries_info @places %>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<%= javascript_include_tag "show_2" %>

<% content_for :head do %>
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@takkyuumap" />
  <meta name="twitter:title" content="<%= @place.title %>" />
  <meta name="twitter:description" content="<%= @place.address %><br>開館時間:<%= raw show_hours_twitter(@place) %>" />
  <% if @place.photos.present? %>
    <meta name="twitter:image" content="<%= @place.photos.first.image.url %>" />
  <% end %>
<% end %>

<div id="notice" style="color:white"><%= notice %></div>

<div class="show_text wf-mplus1p">
  <div class="left_float">

    <h1 class="show_title wf-mplus1p"><%= @place.title %></h1>

    <div class='show_url show-part'>
      <strong>ホームページ</strong><br>
      <div class='url_p'>
        <% if @place.url.size > 0 %>
          <a href=<%= @place.url %> style="color:white"><%= @place.url %></a>
        <% else %>
          未登録
        <% end %>
      </div>
    </div>

    <div class='show_address show-part'>
      <strong>住所</strong><br>
      <div>
        <% if @place.address.present? %>
          <%= @place.address %><br>
          <button type="button" class="btn btn-sm btn-success" href=https://google.com/maps/place/' + <%= @place.address %>>Googleマップで開く</button>
        <% else %>
          未登録
        <% end %>
      </div>
    </div>

    <div class='show_other show-part'>
      <strong>開館時間</strong><br>
      <%= raw show_hours(@place) %>
    </div>

    <div class='show_other show-part'>
      <strong>その他</strong><br>
      <p>
        <% if @place.content.present? %>
          <%= @place.content %>
        <% else %>
          なし
        <% end %>
      </p>
    </div>

    <% if user_signed_in? %>
      <%= link_to '編集', edit_place_path(@place), class:'btn btn-info' %>
    <% else %>
      <button data-toggle='modal' data-target='sign-in-modal' id='sign-in-modal-btn' class="btn btn-info" type="button">編集</button>
    <% end %>
    <%= link_to '戻る', places_path, class:'btn btn-info'%>

  </div>

  <% if @place.photos.present? %>
    <% @place.photos.each do |photo| %>
      <%= image_tag photo.image.url, class: 'show_photo' %>
      <div class='source-text'>画像ソース: <%= photo.source %></div>
    <% end %>
  <% end %>

</div>

<div class="show_map" id="map"></div>

<!-- Modal -->
<div id='sign-in-modal' class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">編集にはアカウントが必要です。</h4>
      </div>
      <div class="modal-body">
        <p>アカウントをお持ちの方は<a href='/users/sign_in'>こちら</a>からログインしてください。</p>
        <p>アカウントをお持ちでない場合は<a href='/users/sign_up'>こちら</a>から作成してください。</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>

  </div>
</div>

<script type="text/javascript">

	var map;

	function initMap() {

    var myLatLng = {lat: <%=@place.latitude %>, lng: <%= @place.longitude %> };

		map = new google.maps.Map(document.getElementById('map'), {
			center: myLatLng,
			zoom: 17
		});

		var marker = new google.maps.Marker({
			position: myLatLng,
			map: map,
      title: "<%= @place.title %>"
		});
	}

</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA1UBETjFq1eApVpLAX-JdAz3tsHf7Bpsc&callback=initMap">
</script>

app/views/places/top.html.erb
<div class="top-text parent vertical-align-parent">
  <div class="child vertical-align-child">
    <span class="wf-mplus1p main_text" style="font-weight:500;">練習場所がない！</span>
    <p class="wf-mplus1p sub_text">そんな人のために、全国の卓球場情報を集約</p>
    <div class="total-div wf-mplus1p" style="font-weight:500;">
      <%= @places_num %>
    </div>
    <div class="wf-mplus1p num_text">合計卓球場登録数</div>
    <div class="twitter_div">
      <p class="wf-mplus1p sub_text">SNSでシェア</p>
      <p><a href="https://twitter.com/share" class="twitter-share-button" data-url="https://takkyuumap.com" data-text="全国450以上のの卓球場情報を集約した「卓球マップ」、現在地や地名から検索も！" data-hashtags="卓球マップ">Tweet</a></p>
    </div>
  </div>
</div>

<div class="parent_circle vertical-align-parent">
  <div class="vertical-align-child">
    <div class="top">
      <p class="wf-mplus1p">地名で検索</p>
      <%= form_tag({ controller: :places, action: :map}, {method: :get}) do %>
        <div class="input-group top_input">
          <%= text_field_tag :search, '', class: 'form-control' %>
          <span class="input-group-btn">
            <%= submit_tag '検索', class: 'btn btn-secondary' %>
          </span>
        </div>
      <% end %>
    </div>
    <div class="bottom">
      <%= link_to '現在地から検索', map_path(current: true), class: "wf-mplus1p circle left" %>
      <%= link_to '一覧を表示', places_path, class: "wf-mplus1p circle right" %>
    </div>
  </div>
</div>

<div class="mobile_twitter_div text-center">
  <p class="wf-mplus1p sub_text">SNSでシェア</p>
  <p><a href="https://twitter.com/share" class="twitter-share-button" data-url="https://takkyuumap.com" data-text="全国450以上のの卓球場情報を集約した「卓球マップ」、現在地や地名から検索も！" data-hashtags="卓球マップ">Tweet</a></p>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>